#!/bin/bash
# Aizoniq Live Server Update Script
# Upload these files to your live server

echo "📦 Files to Update on Live Server:"
echo "=================================="
echo ""
echo "CORE FILES:"
echo "  ✓ index.html - Updated with chatbot container"
echo "  ✓ src/main.js - Fixed ThemeSwitcher import"
echo ""
echo "CHATBOT & COMPONENTS:"
echo "  ✓ src/components/chatbot/chatbot.js - Fixed theme reference"
echo "  ✓ src/components/theme-switcher/theme-switcher.js - Theme switcher component"
echo ""
echo "i18n & THEME SYSTEMS:"
echo "  ✓ src/i18n/i18n.js - Translation system"
echo "  ✓ src/theme/theme.js - Theme management"
echo ""
echo "STYLES:"
echo "  ✓ css/variables-theme.css - CSS variables (light/dark)"
echo "  ✓ css/chatbot-modern.css - Modern chatbot styles"
echo "  ✓ css/theme-switcher.css - Theme switcher styles"
echo ""
echo "=================================="
echo ""
echo "Quick Action Items:"
echo "1. Upload the files above to your live server"
echo "2. Clear browser cache (Ctrl+Shift+Delete)"
echo "3. Refresh the page (Ctrl+F5)"
echo "4. Open developer console (F12)"
echo "5. Check that:"
echo "   - Chatbot appears in bottom-right corner"
echo "   - Language/Theme buttons appear in header"
echo "   - No errors in console"
echo ""
echo "Test Commands in Console:"
echo "  → i18n.setLanguage('ar')"
echo "  → themeManager.toggle()"
echo "  → document.querySelector('#chatbot-widget')"
echo ""
